### ISSUE TITLE
Add the ability to exclude callstack details on well performing requests sent to Elasticsearch

### ISSUE THREAD

**Issue by ryanrupp** [stagemonitor/stagemonitor#124]
This would be to reduce the overall amount of data sent to Elasticsearch but basically would like the ability to say something like, only send the callstack if:

1) The request took over X ms
2) The request resulted in an exception/error

This could be either in the form of a Stagemonitor supported configuration or even a hook point to allow applications to modify the data that is sent to Elasticsearch (basically there's already the reporter interface but something like an advisor to the Elasticsearch reporter that allows modifying the RequestTrace). Note that the request data for every request would still be sent just the call stack would be omitted under certain conditions.

Let me know if you think this makes sense as a standard feature and I can probably put together a pull request at some point.

**Comment by felixbarny** [comment]
I like the idea of the hook point. I'm thinking of an interface that you can implement to either stop reporting to Elasticsearch or to exclude certain properties. The `ElasticsearchRequestTraceReporter` then loads all implementations of that interface via a `ServiceLoader`. I would also extract the methods `isReportRequestTraceName` and `isReportingRateExceeded` to a implementation to that interface.

A simple configuration for the request duration might not be enough, because you may want to configure different thresholds for different business transactions.

**Comment by felixbarny** [comment]
Regarding making it a standard feature, maybe it would make more sense to be able to configure a percentile threshold. What I mean by that is that reporting the call tree should only happen if the request took longer than, for example the 85% percentile of the same use case. The problem with the static 'more than x millis' approach is that each use case has its own performance characteristics. So a search suggestion that takes more than 100ms could be considered slow while 1 second for rendering the search result is fast. The percentile approach automatically takes that into account and only reports if a request of a particular use case is slower than normal.

**Comment by ryanrupp** [comment]
Yeah that makes sense, I believe this is what AppDynamics is doing when it decides to take a full request trace, it creates baselines based on historical data and will capture a full trace when a request falls into what is "slow" (or ends in an error) based on the baseline which is nicer than static thresholds.

For that could either:
1) Compute percentiles based off the transaction name via Elasticsearch saved request traces so there's a percentile threshold by transaction name of when to actually report the details. This would be the most accurate but requires Elasticsearch be used and that Stagemonitor has the ability to query elasticsearch.
2) Use the metrics timers that are tracking response time by request name - not the most accurate due to how weighting of the distribution works with timers.

**Comment by felixbarny** [comment]
I had the second approach in mind. Why do you think this is not accurate?
It would be cool to know whether a request will be slow before it has finished. That way I could decide whether or not to collect a call tree. Because not collecting it is much more efficient than not reporting it. That's some kind of dilemma...

**Comment by ryanrupp** [comment]
Accurate probably wasn't the right word, it's more if should the baseline that's being used be computed from ~ the last 5 minutes of timings or across a day/week etc. With the metrics timers it's using a exponentially decaying reservoir with 1028 timings in the reservoir to compute the percentiles. It's using weighting to favor more recent timings when evicting from a reservoir that has hit the capacity limit. The javadoc mention it's basically biasing towards timings within the last 5 minutes. So, the reporting sampling pattern then would be something like "report this if the time was > the 85th percentile time looking at an approximate distribution of last 5 minutes" vs reading from Elasticsearch you could get those baselines from a larger window e.g. 85th percentile across one day/week (provided the data was there). I think either is good though, using the metrics timers makes it so there's no dependency on elasticsearch query access and worst case you probably just end reporting more than needed (which isn't a big deal).

As for sampling patterns as you mentioned I see two main areas:
1) Post-sampling decision (topic of this post - reporting of collected trace) e.g. given a request trace that has already occurred, do the characteristics of it mean that it should actually be reported to Elasticsearch. This is more of a benefit for the network and storage service (Elasticsearch) in that you can exclude some of the detail data that it has to ingest - I actually requested this because Kibana was choking for me sometimes if I accidentally did a search without filtering the columns and I believe this was because of pulling all the call stack details back when for the majority of requests I didn't need the call stack details (requests that performed as expected).
2) Pre-sampling decision e.g. should I trace this request in detail (callstack tracing). As you mentioned this ones a bit harder because you're basically trying to make an educated guess towards the future of the request (will this request be slow or end in an error). Reducing unnecessary trace requests can reduce application load. For this the approach could be something fairly simple like "only sample every X requests" or a smarter adaptive approach using other criteria e.g. the request name/user/previous behavior for the given request name, whatever is available at the time to try to come to a decision. The Google Dapper paper has some good insight about this in section 4 "Managing Trace Overhead" - http://static.googleusercontent.com/media/research.google.com/en//pubs/archive/36356.pdf - I think the takeway there was for low traffic applications you can get away with sampling everything and for high traffic applications so many requests are coming through them that if you run into a slow/errored request you'll likely see it again even when doing some lower rate of sampling e.g. sample 1 in every 1024 requests but mentions they were going to move to a more adaptive sampling pattern.

That could be another nice hookpoint for Stagemonitor at some point, have to stress that coming to that pre-sampling decision should be performant though if allowing custom implementations to be provided as it's done inline with the request (vs reporter interceptor is done in another thread). I think generally Stagemonitor should capture all requests at a high level (name/url/how long it took etc.) just the callstack tracing could be sampled out potentially in some way.

**Comment by felixbarny** [comment]
OK, I see what you mean. 
> "report this if the time was > the 85th percentile time looking at an approximate distribution of last 5 minutes" 

I also think this is good enough. Will probably implement this. The baseline approach is probably more suited to alerting. For limiting the call tree reporting this seems like an overkill.

> mentions they were going to move to a more adaptive sampling pattern.

This is exactly what stagemonitor is already offering for request trace sampling via the configuration parameter [`stagemonitor.requestmonitor.onlyReportNRequestsPerMinuteToElasticsearch`](https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#only-report-n-requests-per-minute-to-es). There also is an option to sample the call tree creation `stagemonitor.profiler.collectCallTreeEveryNRequests`. Though it would probably make more sense to also configure the rate rather than the percentage of requests where a call tree should be collected. I also thought long about introducing something more sophisticated like determining which use case is slower than in the past. But that means I have to know the request name before the measurement starts. This is where it gets tricky and I just recently removed the support for that in https://github.com/stagemonitor/stagemonitor/commit/332e27a52cd36dc2e7e58e507589b6c9af94f1d6. I think the simple sampling approach is good enough for that use case.

**Comment by felixbarny** [comment]
Implemented in #125
