### ISSUE TITLE
Add Prometheus Support

### ISSUE THREAD

**Issue by shpsec-dennis** [stagemonitor/stagemonitor#157]
Hi- this is a request to add Prometheus (http://prometheus.io) as a backend for stagemonitor.

**Comment by felixbarny** [comment]
This actually shouldn't be too difficult. The implementation would very much look like this: https://github.com/prometheus/client_java/blob/0c4a31517147ec4722f0160b7ad59a40d0c4e8a4/simpleclient_dropwizard/src/main/java/io/prometheus/client/dropwizard/DropwizardExports.java.

The difference is that stagemonitor natively supports the key-value based format so that the label names and values List (https://github.com/prometheus/client_java/blob/0c4a31517147ec4722f0160b7ad59a40d0c4e8a4/simpleclient/src/main/java/io/prometheus/client/Collector.java#L81) can be properly converted from stagemonitor's [`MetricName#tags`](https://github.com/stagemonitor/stagemonitor/blob/6d477f49afaf11c7af747f873784557b056ffec7/stagemonitor-core/src/main/java/org/stagemonitor/core/metrics/metrics2/MetricName.java#L24).

Do you feel like contributing the reporter?
