### ISSUE TITLE
Question: What is the future of dropwizard metrics registry compatibility

### ISSUE THREAD

**Issue by marcust** [stagemonitor/stagemonitor#163]
I just played around with 0.25 and saw all the changes you did to the metrics registry. I'm now wondering where you plan on going from there, because in our usecase we cheated right now when it came to other Dropwizard metrics (e.g. HikariCP, Hystrix, etc) and used the same shared MetricRegistry for everything and let Stagemonitor ship all of it to Graphite. When you now start to kill that "feature" we would need a different way of doing that.

**Comment by felixbarny** [comment]
The problem with the dropwizard metrics registry is that it only lets you properly report to what I call metrics 1.0 databases like Graphite where you have one dimensional metric names like `<app>.<host>.<instance>.cpu.usage`. To properly support reporting to metric 2.0 databases like InfluxDB, Elasticsearch, OpenTSDB, ... which are build around multi dimensional tags, I implemented the Metrics2Registry, which is fully backwards compatible to metric 1.0 names.

For your use case you can also get the "legacy" dropwizard registry which is associated with the Metrics2Registry via `Metric2Registry#getMetricRegistry` and register your 1.0 metrics there. These metrics then of course can't be reported to metric 2.0 databases.

If you do wish to report to a metrics 2.0 database but using 3rd party dropwizard plugins, you can for example use the utility method `org.stagemonitor.core.metrics.metrics2.Metric2Set.Converter#convert` to convert 1.0 style metric names into 2.0 style metric names. See `org.stagemonitor.jvm.JvmPlugin#initializePlugin` for an example. Otherwise, when you wrote the HikariCP, Hystrix, etc collection code yourself, you can simply upgrade the metric names from `String` to `org.stagemonitor.core.metrics.metrics2.MetricName`.

**Comment by felixbarny** [comment]
Is that good enough for your use case?

**Comment by marcust** [comment]
It is... I just wanted to make sure that you do not drop the support for the "legacy" metrics registry anytime soon.

**Comment by remmeier** [comment]
FYI: created https://github.com/dropwizard/metrics/issues/964 to add support in dropwizard

**Comment by ryanrupp** [comment]
Tagged based naming is slated for Metrics 4.0, see [MetricName](https://github.com/dropwizard/metrics/blob/master/metrics-core/src/main/java/io/dropwizard/metrics/MetricName.java) on master

**Comment by remmeier** [comment]
great, will stagemonitor upgrade to that?

**Comment by felixbarny** [comment]
Yes, if it will release some day...
