### ISSUE TITLE
Integration with JBoss 5.1

### ISSUE THREAD

**Issue by domtoupin** [stagemonitor/stagemonitor#171]
I am also trying to use stagemonitor with JBoss 5.1; so far I managed to get the stagemonitor-os and stagemonitor-jvm plugins working but I am still having issue with stagemonitor-requestmonitor and stagemonitor-jdbc.

I had to build my own jackson-module-afterburner-2.7.4 jar in order to make it run under java 6 (the most recent java version supported by JBoss 5.1)

I used the same options as I did for my Wildfly 10 setup with one exception: I did not add `org.jboss.as.connector.subsystems.datasources.WildFlyDataSource` to `stagemonitor.instrument.jdbc.dataSource.implementations`

When I set `stagemonitor.instrument.debug` to `true`, I do not have any transformation performed by RemoteEjbMonitorTransformer. However, I do have a warning I didn't have back on Wildfly 10:
```
2016-06-15 11:37:42,961 INFO  [org.stagemonitor.core.Stagemonitor] (stagemonitor-startup) Initializing plugin RequestMonitorPlugin
2016-06-15 11:37:43,083 WARNING [com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector] (stagemonitor-startup) Unable to load JDK7 annotation types; will have to skip
```

Could this be related to my issue? Is there anything else I can look at to try to figure out what is going on? Is stagemonitor supposed to work under Java 6?

Again, thank you very much for your help!

**Comment by felixbarny** [comment]
Java 6 is supported. The afterburner module is only applied when [Java version is > 1.6](https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-core/src/main/java/org/stagemonitor/core/util/JsonUtils.java#L24).

I don't think that the jackson warning is related to your issue.

If you are willing to dive into it, your best bet is to extend `RemoteEjbMonitorTransformer` and override `onIgnored` like so:

```
	@Override
	public void onIgnored(TypeDescription typeDescription, ClassLoader classLoader) {
		if (DEBUG_INSTRUMENTATION && typeDescription.getName().contains("YourRemoteEjb")) {
			
		}
	}
```

In there, you can evaluate expressions to see which matcher excludes your class. You can also take a look at the `onIgnored` method of [`ConnectionMonitoringTransformer`](https://github.com/stagemonitor/stagemonitor/blob/8fc4d5ec3c9729ab435aa9ea52a6b5e328199a92/stagemonitor-jdbc/src/main/java/org/stagemonitor/jdbc/ConnectionMonitoringTransformer.java#L70-L70)

Then, register your implementation in `src/main/resources/META-INF/services/org.stagemonitor.core.instrument.StagemonitorByteBuddyTransformer`. See https://github.com/stagemonitor/stagemonitor/blob/37b46be00437c84191a334d378c2ae643a2bb497/stagemonitor-requestmonitor/src/main/resources/META-INF/services/org.stagemonitor.core.instrument.StagemonitorByteBuddyTransformer#L5-L5

Otherwise it would be really helpful if you could provide a small example application so that I can debug the problem.

I will try to add better debugging capabilities for that into stagemonitor.

**Comment by domtoupin** [comment]
After debugging, I can see that my beans are indeed transformed (e.g. `FINE  [org.stagemonitor.core.instrument.StagemonitorByteBuddyTransformer] (main) TRANSFORM com.company.services.beans.LoaderBean (RemoteEjbMonitorTransformer)`). However, it seems that, unlike on Wildfly 10, `org.stagemonitor.requestmonitor.AbstractMonitorRequestsTransformer.monitorStart(String, Object[], String, String, String, Object)` is not called when a remote call is made.

Where should I look next?

**Comment by domtoupin** [comment]
... Guess what? It works perfectly, once the client is configured perform requests on the right server... 

Sorry to have bothered and thank you for your time!
