### ISSUE TITLE
Single .jar file for agent

### ISSUE THREAD

**Issue by Ykisialiou** [stagemonitor/stagemonitor#240]
Hello. Thanks a lot for a great tool. I'm just curios, is it possible to have stagemonitor as a single .jar agent, that can be attached to app by adding -javaagent option on startup?
It so, it will  ease installation process for ops engineers and will be great improvement for cloud based deployments.  Great thank again.

**Comment by felixbarny** [comment]
Hi @Ykisialiou,

no, that is not possible. I'd suggest getting in touch with the developers and to include stagemonitor in the project. They don't even have to use it if they don't want - you can configure stagemonitor so that is only active in production.

The way we see it, stagemonitor's approach is actually more maintainable, user friendly and especially suited for dev-ops organizations. Let's suppose you want do deploy and monitor a spring boot application. The first step is to copy the app.jar to your production server. Then you need to start the application with `java -jar app.jar -javaagent:agent.jar`. But where does the agent.jar come from? You need a separate deploy process for it and need to make sure to update it on all your hosts when a new version comes out. But what if you don't want to immediately use the new version in your production environment but only on your test/staging env? Things start to become more difficult to maintain now. These exact problems are already solved within the java community by dependency management systems like maven or gradle. Back to your spring boot application. Here you'll have a similar requirement. You first want to test new versions of spring (or any other dependencies) in your test environment to make sure that it does not affect your application. This is exactly how you can manage updates to stagemonitor as well - just update your pom.xml or build.gradle and your application contains the specified version of stagemonitor. Your spring boot app is now truly self-contained: It contains the embedded server and the monitoring code. There is no need for external libraries to be deployed to your severs which makes the deploy process more stream-lined and standardized. It might be a different approach than most operators are used to. Maybe it will be strange for your developers at first as well when operators modify the pom.xml. But if you try out this new approach, you will quickly see the benefits of it.

We also believe that performance is not only something operators should be interested at. There should be a collaboration between devs and ops. This collaboration will be much easier when both are using the same tool.

Thanks for the question :)
