### ISSUE TITLE
StageMonitor on Vert.x 3 web router

### ISSUE THREAD

**Issue by glamarre360** [stagemonitor/stagemonitor#249]
Is there a way for stagemonitor to push data on request made on a Vert.x3 web router.

**Comment by glamarre360** [comment]
I've manage to collect the data by dropwizard implementation pushing in the stagemonitor MetricRegistery but i can't see any of this data in kibana

**Comment by felixbarny** [comment]
Stagemonitor currently can't collect request metrics and traces in Vert.x applications. However you can collect metrics like from the JVM and the Operating System.
In order to see the metrics in Kibana, you have to configure stagemonitor to send its metrics to elasticsearch: https://github.com/stagemonitor/stagemonitor/wiki/Elasticsearch#configuration

**Comment by glamarre360** [comment]
I've managed to push the vert.x metrics to the legacy dropwizard registry but those metrics aren't sent to elasticsearch.

**Comment by glamarre360** [comment]
I've edited the code so it use the Metric2Registery and now everything work.
