### ISSUE TITLE
Unable to connect to ES 5.6.2

### ISSUE THREAD

**Issue by rsinha9** [stagemonitor/stagemonitor#329]
I am trying to integrate stagemonitor into an existing Java 1.7.0_80 project, and when trying to connect to elasticsearch 5.6.2 on my local, it fails to think that elasticsearch is available. Digging into the code a little bit looks like HEAD call that happens to elasticsearch for status fails with a "java.net.ProtocolException: HTTP method HEAD doesn't support output" exception when it attempts to get the pass the output stream from the HttpUrlConnection to the request.
```
if (request.getOutputStreamHandler() != null) {
    request.getOutputStreamHandler().withHttpURLConnection(connection.getOutputStream());
}
```
Looking at the calling code, the response isn't even used, so we could potentially pass null as the output stream handler for this call in order to not fail in this instance. Has anyone else run into this issue? I'm happy to fix and create a PR for this, but want to make sure it isn't a configuration issue before I do that.

**Comment by felixbarny** [comment]
Thanks for raising this issue. Strangely, I don't get this exception. I think the problem is that `outputStreamHandler` is initialized with `NoopOutputStreamHandler.INSTANCE`: https://github.com/stagemonitor/stagemonitor/blob/265f08ce3b861907c756a7a2b14aff95de32e35e/stagemonitor-core/src/main/java/org/stagemonitor/core/util/http/HttpRequestBuilder.java#L30.

All it does is to close the `outputStream` but I don't think that's necessary. I think we could just remove `NoopOutputStreamHandler` and initialize `outputStreamHandler` with null.

@trampi what do you think? What was the intention of `NoopOutputStreamHandler`?

**Comment by rsinha9** [comment]
Makes sense, I was thinking of just making it null for this case because I wasn't sure what all it would impact, but since it is just closing the output stream, seems safe to just remove it.

**Comment by trampi** [comment]
After thinking about it, `null` would probably be the better choice for the default response handler. I used `NoopResponseHandler` as default in the `HttpRequestBuilder`, because the original code had this comment: `// we have to read the whole response, otherwise bad things happen`.

**Comment by felixbarny** [comment]
The `NoopResponseHandler` makes perfect sense but I don't think a `NoopOutputStreamHandler` is needed. The latter one is responsible for writing into the request body.

**Comment by trampi** [comment]
Mixed that up while writing the response, sorry ;-)

A `NoopOutputStreamHandler` does not make sense indeed. I was not aware, that `connection.getOutputStream` could throw e.g. for HEAD requests. Given that it could cause errors (and that we have a replacement), we should remove it.

**Comment by rsinha9** [comment]
I've created PR https://github.com/stagemonitor/stagemonitor/pull/331 for this.
