### ISSUE TITLE
Collect SQL Queries in the Dashboard

### ISSUE THREAD

**Issue by tstaals** [stagemonitor/stagemonitor#89]
When using stagemonitor in production , you do lose the capablitly of viewing the executed queries.

It would be nice when the excuted queries would some how been pushed to the dashboard where you could sort on execution time, this way you can find queries that take a long time to execute.

**Comment by felixbarny** [comment]
What do you mean by "in production"? Which settings differ there? Can't you see the execution time of the SQLs in the DB Query dashboard?

![](http://www.stagemonitor.org/images/dashboard-db-5226318f.png)

**Comment by tstaals** [comment]
I mean something in the line of new-relic

![image](https://cloud.githubusercontent.com/assets/513068/8574459/0c511f6c-2597-11e5-8f8f-61469ed87e8c.png)

The DB Queries screen does give us timings , but the way our app is organized , we cannot trace it back.

**Comment by felixbarny** [comment]
I see. The Kibana request dashboard contains that information: https://github.com/stagemonitor/stagemonitor/wiki/Request-and-Call-Stack-Dashboard#request-details

It is also possible to display the in browser widget in production for authorized users: https://github.com/stagemonitor/stagemonitor/releases/tag/0.13.0

**Comment by tstaals** [comment]
I see thanks, at the moment it does require to have enable the call stack. It would be nice if you could disable the stacktrace but still capture and log the executed queries.

**Comment by felixbarny** [comment]
One way to do that would be to disable the Profiler so the call tree would only show SQLs

**Comment by felixbarny** [comment]
Just brainstorming on how I want to implement it. Introducing a separate stagemonitor-sql* index where statements are stored. Data model:

```
executedBy: closest (dao) method in the call stack which is inside the monitored project. This does not depent on the profiler but instead looks at the current threads stack trace. 
executionTime: time in ns (or ms?)
statement: the sql statement
requestTraceId: allows to find all sqls of a particular request. 
requestName: allows for example to get the 10 slowest SQLs of a particular request (like shown in the new relic screenshot)
```

Simmilar rate limiting config options like the call tree has. Max recorded sqls per minute. Not quite sure about the default yet. 1 per minute seems reasonable or 0 to deactivate by default or no limit to not confuse people why there oly some sqls, though i wouldnt recommend that in prod. Ability to omit reporting when the execution was fast. 

One alternative would be to include the sqls in the request traces (sragemonitor-requests). But that might bloat them. 

@ryanrupp what do you think about this?

Relates to #143

**Comment by felixbarny** [comment]
Probably a `stagemonitor-external-requests-*` index would be better which also contains elasticsearch queries and in the future other requests like http or mongodb calls as well. Add a `type:sql|elasticsearch|···` discriminator property.

**Comment by ryanrupp** [comment]
I like the idea of the "stagemonitor-external-requests" with the different types under it for different external services. As for the data model:

1) executedBy - you mentioned you would look at the callstack for this, if you're doing this inline with the request then I think this is somewhat of an expensive action. Also, how are you determining what's a DAO? This may be already be done in Stagemonitor I just missed it.
2) executionTime - ms is okay with decimals for further precision. I looked at P6Spy and it only tracks millisecond precision. Weird thing about P6Spy is it looks like it's using System.currentTimeMillis() for time tracking which doesn't really have that great of granularity for timing operations. I remember on Windows 2008 for instance System.currentTimeMllis() only has like 15.5ms precision. I didn't really dig into this too much just something I thought was interesting. Wonder why it doesn't use System.nanoTime(), maybe backwards compatibility has kept it from being changed.
3) statement - can have a follow up to provide a custom field formatter for the SQL in Kibana :), assuming at least this is not being pretty formatted before being sent.
4) Would the common request attributes be included in this e.g. host/app/instance? It would be redundant but it's nice to slice on this on data e.g. query counts by host.

Here's what Elastic's packetbeat captures for MySQL in comparison, P6Spy doesn't capture all of that but that's fine really, mostly interested in the statement + timings, if it errored would be nice but the request itself will capture that. I have used the "method" field to slice on reads vs writes as I'm interested in the read/write ratio:

```
"_source": {
    "@timestamp": "2016-04-12T00:08:56.760Z",
    "beat": {
      "hostname": "ip-172-31-16-227",
      "name": "bcs-devere-dev"
    },
    "bytes_in": 13,
    "bytes_out": 56,
    "client_ip": "172.31.16.227",
    "client_port": 41681,
    "client_proc": "",
    "client_server": "",
    "count": 1,
    "direction": "out",
    "ip": "172.31.19.33",
    "method": "SELECT",
    "mysql": {
      "affected_rows": 0,
      "error_code": 0,
      "error_message": "",
      "insert_id": 0,
      "iserror": false,
      "num_fields": 1,
      "num_rows": 1
    },
    "path": ".",
    "port": 3306,
    "proc": "",
    "query": "select 1",
    "responsetime": 0,
    "server": "",
    "status": "OK",
    "tags": [
      "bcs",
      "devere",
      "dev"
    ],
    "type": "mysql"
  }
```

**Comment by felixbarny** [comment]
1) I don't think this is a performance issue as the following JDBC call probably is magnitudes slower (network latency, DB processing, ...). Performance could probably improved using `SharedSecrets.getJavaLangAccess().getStackTraceElement(exception, frame);`. See http://stackoverflow.com/a/26122232/1125055. But I don't know if using JDK internal classes is such a good idea.. Also, I already do this in [StagemonitorP6Logger](https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-jdbc/src/main/java/org/stagemonitor/jdbc/p6spy/StagemonitorP6Logger.java#L60) (since [0.23.0](https://github.com/stagemonitor/stagemonitor/releases/tag/0.23.0)) to create a timer for each JDBC statement. The DAO method is just defined as the closest method in the stack trace which is inside the monitored project. In other words your method which triggered a JDBC call. Previously, I got the DAO method from the call tree but this obviously does not work if the profiler is not active.

2) 
> ms is okay with decimals for further precision.

I agree. This would then be in line with other metrics.

> looked at P6Spy and it only tracks millisecond precision

Yes, I know, that's a bit sad. I already had a discussion about this with the guys from p6spy and they created this issue: https://github.com/p6spy/p6spy/issues/295. Unfortunately, it's already a year old.

3)
> can have a follow up to provide a custom field formatter for the SQL in Kibana

That would be truly awesome :) How would you format the SQL string? I too was looking for a Java or JavaScript based SQL pretty printer but found none.

4) Good catch. I'll definitely include those. Adding the method also is a good idea and should be easy to implement as it's just the first term in the SQL string. I've also [requested](https://github.com/p6spy/p6spy/issues/298) access to more information like the number of returned rows. I should probably start making more pull requests for p6spy. If you feel like contributing there go for it. They are very nice guys and are open to improvements.

**Comment by felixbarny** [comment]
I've started working on this on the [external-requests](https://github.com/stagemonitor/stagemonitor/tree/external-requests) branch.

**Comment by felixbarny** [comment]
I've created a pull request for this: #159

How do you like it?
