### ISSUE TITLE
BoomerangJsHtmlInjector Is Injecting Even With RUM Disabled

### ISSUE THREAD

**Issue by swillson** [stagemonitor/stagemonitor#95]
Based on the code in ```BoomerangJsHtmlInjector``` it injects a HTML snippet even if RUM is disabled. The snippet doesn't put a URL in to BOOMR but everything else is injected even if you set ```stagemonitor.web.rum.enabled=false```. I'd think the ```BoomerangJsHtmlInjector``` should return an empty string in the ```buildBoomerangTemplate``` method. I'd think that nothing at all should be injected when disabled.

Is there another different way to disable this now?

**Comment by felixbarny** [comment]
This is the expected behavior - the boomerang script snippet is injected if RUM is enabled or if the in browser widget is shown. 

This is necessary to display the page load time in the request tab.
![page-load-time](https://cloud.githubusercontent.com/assets/2163464/9468837/12774f56-4b44-11e5-8467-f59d7c9fd7fd.png)

If the widget is enabled but rum not, the page load time data is not reported to the server (the `beacon_url` is not set).

If both options are disabled, the snippet won't be injected (see `BoomerangJsHtmlInjector#isActive`)

Does this break anything on your website? Do you have a suggestion of what should behave differently?

**Comment by swillson** [comment]
Our configs are the following:

```stagemonitor.web.widget.enabled=false
stagemonitor.web.rum.enabled=false
stagemonitor.profiler.logCallStacks=false
stagemonitor.reporting.interval.console=0
stagemonitor.configuration.reload.interval=600
```

So we're disabling both the widget and RUM yet it's still injected. Should I exclude these via the ```stagemonitor.plugins.disabled``` property instead?

**Comment by felixbarny** [comment]
I don't see how you are disabling the widget (`stagemonitor.web.widget.enabled`).

Btw
```
stagemonitor.profiler.logCallStacks=false
stagemonitor.reporting.interval.console=0
```
is the default. You don't have to explicitly set this

**Comment by swillson** [comment]
Its in the above, the formatting was off and had to edit it (see above again, its false) ... It think the bug may be elsewhere based on your code path. In the ```isWidgetAndStagemonitorEndpointsAllowed``` this logic statement I think should be an && not an ||.

```final boolean result = widgetEnabled || passwordInShowWidgetHeaderCorrect;```

Thoughts? We don't have a password set at all, so setting one may fix this but to be honest that makes no sense as we don't want it enabled at all.

**Comment by felixbarny** [comment]
Is the widget displayed? Do you have the password set to an empty String (`stagemonitor.password=`)?

**Comment by swillson** [comment]
Ok, so this problem is slightly weird ... I was able to get around it by NOT setting this property:

```stagemonitor.password=```

We were setting this to nothing which I think was there from an old version of StageMonitor. But by setting it to nothing it always enabled that widget based on that logic statement above. So by not setting this property it seems to not inject. Something about that is weird though as we disabled the widget itself which should be the big hammer of disabling.

**Comment by felixbarny** [comment]
By 'this property' you mean `stagemonitor.password`?

**Comment by swillson** [comment]
Yea ... If we're trying to disable the widget one would think that setting ``` stagemonitor.web.widget.enabled=false ``` should be the larger hammer to anything. If that is true then it should check the password. We'll unset the password, remove from file, but that seems like a byproduct fix and not an actual fix. Thoughts?

**Comment by felixbarny** [comment]
I admit that this is a bit counter intuitive. Maybe you could help us to find a better way. Basically, this is a security feature.

This is the reason behind it:
Not setting `stagemonitor.password` basically disables any dynamic updates. It serves as a secure default setting. So that by default no malicious user can mess with your stagemonitor configuration.

When in development, you typically don't need a password and security as it's just you accessing the application on your local machine. So you set `stagemonitor.password=`.  That way you can dynamically change the configuration in the widget without specifying a password.

In Production, it is fatal to set `stagemonitor.password=` as anyone could mess with your configuration. It is even possible to display the widget if `stagemonitor.web.widget.enabled` is set to `false` by sending the header `X-Stagemonitor-Show-Widget: <stagemonitor.password>` so that authorized users can enable the widget in production (`widgetEnabled || passwordInShowWidgetHeaderCorrect`). If you set `stagemonitor.web.widget.enabled=false` you could have the wrong assumption that your users can't see the widget and therefore can't mess with your configuration, so you might forget to remove `stagemonitor.password=` or set a real password. That's why the widget is displayed, even if you told it not to as anyone could re-enable it.

A good thing would to show a waring in the widget that tells you that the widget is visible because the password is empty.

If you do want to disable it, the best thing would be to specify a password or unset `stagemonitor.password`.

I'm very open to suggestions as I know this is really confusing...

**Comment by felixbarny** [comment]
Any thoughts?
