### ISSUE TITLE
Classes setting properties that are not Strings

### ISSUE THREAD

**Issue by anelson425** [stagemonitor/stagemonitor#99]
The ConnectionMonitoringInstrumenter class is setting the CONNECTION_MONITOR property with a value of type ThreadLocal[1]. The StagemonitorAgent class is setting the INSTRUMENTATION_KEY property with a value of type Instrumentation.

The documentation on the Properties class[3] says that each key/value here are both to be strings. We are using this library and a Clojure library at the same time. At runtime, Clojure validates the key/values are all strings so this is causing us issues trying to use both libraries at the same time.

[1] https://github.com/stagemonitor/stagemonitor/blob/f5da75d97731fe9271648a2144b572b0957b30b3/stagemonitor-jdbc/src/main/java/org/stagemonitor/jdbc/ConnectionMonitoringInstrumenter.java#L62
[2] https://github.com/stagemonitor/stagemonitor/blob/0.17.2/stagemonitor-javaagent/src/main/java/org/stagemonitor/agent/StagemonitorAgent.java#L55
[3] http://docs.oracle.com/javase/7/docs/api/java/util/Properties.html

**Comment by felixbarny** [comment]
I'm using this 'trick' `System.getProperties().put("some string", someObject);` to share objects across classloaders. Do you happen to know a better way? What is the exact error you get?

**Comment by mrrodriguez** [comment]
This relates to a Clojure issue that was Declined and claimed to be an issue to log to the offending libraries.  This issue is http://dev.clojure.org/jira/browse/CLJ-1717.

This particular Clojure Jira was decline and the fix was pushed at the offending Eclipse bug, which is mentioned there at https://bugs.eclipse.org/bugs/show_bug.cgi?id=445122.  I'm not sure if they were using this for the same classloader sharing behavior you have.

The Clojure runtime expects to be able to loop through all of the `System.getProperties()` to find properties it is searching for.  It makes the somewhat aggressive decision of casting all of the key-value pairs of the Properties to Strings prior to checking them.  Thus we get a ClassCastException on this `someNotStringObject` property value.  

Although this behavior is "aggressive" it is in compliance with the general contract of the Properties class mentioned above under [3].  Specifically calling `Properties.put()` or `Propteries.putAll()` is strongly discouraged, in favor of `Properties.setProperty()` on any Properties object because it causes a "compromised" state of the Properties object that will throw on invocation of many of its public API method.

I think this class is a bit of a "type system fail" on the Java-side, but it is probably historical.  It would seem to me to be a dangerous practice to put something in the global System properties though that "compromise" the state of those Properties for all consumers.

**Comment by felixbarny** [comment]
I'll try to come up with a better way to do that as soon as I find time. If you want to give it a shot go for it.

**Comment by nickgr6** [comment]
Hi @felixbarny, I also currently have problems relating to this bug.
This bug results in a Tomcat startup failure when activating Stagemonitor in a project which is also using Apache Ignite (web session sharing). 

Apache Ignite calls the 'java.util.Properties.store()' method, which results in executing the following code:
`private void store0(BufferedWriter bw, String comments, boolean escUnicode)
        throws IOException
    {
        if (comments != null) {
            writeComments(bw, comments);
        }
        bw.write("#" + new Date().toString());
        bw.newLine();
        synchronized (this) {
            for (Enumeration<?> e = keys(); e.hasMoreElements();) {
                String key = (String)e.nextElement();
                String val = (String)get(key);
                key = saveConvert(key, true, escUnicode);
                /* No need to escape embedded and trailing spaces for value, hence
                 * pass false to flag.
                 */
                val = saveConvert(val, false, escUnicode);
                bw.write(key + "=" + val);
                bw.newLine();
            }
        }
        bw.flush();
    }`

The line which fails is casting the properties value to a String:
`String val = (String)get(key);`

The following Stagemonitor classes adds an incorrect object (instead of String) value to the system properties:
**MainStagemonitorClassFileTransformer**:
`			System.getProperties().put(IGNORED_CLASSLOADERS_KEY, Collections.newSetFromMap(new ConcurrentHashMap<Integer, Boolean>()));
`
**StagemonitorAgent** (2 occurrences in this classs):
`
System.getProperties().put(INSTRUMENTATION_KEY, inst);
System.getProperties().put(INSTRUMENTATION_KEY, instrumentation);
`
**ConnectionMonitoringInstrumenter**:
`
System.getProperties().put(CONNECTION_MONITOR, connectionMonitorThreadLocal);
`

I think you could replace all these occurences and instead use a Singleton pattern, to store properties which should only exists once.

For example see: http://www.javaworld.com/article/2073352/core-java/simply-singleton.html

Do you think you can fix this bug?

**Comment by felixbarny** [comment]
With the singleton pattern, you can't share objects across class loaders. I'll try to come up with a solution but its quite tricky.

**Comment by nickgr6** [comment]
Maybe the following explanation helps:

> 2. if you are using multiple classloaders, this could defeat the Singleton implementation and result in multiple instances. 

> Solution:

> Because multiple classloaders are commonly used in many situations—including servlet containers—you can wind up with multiple singleton instances no 
> matter how carefully you've implemented your singleton classes. If you want to make sure the same > classloader loads your singletons, you must specify the 
> classloader yourself; 

See full text and example on: http://snehaprashant.blogspot.nl/2009/01/singleton-pattern-in-java.html

**Comment by felixbarny** [comment]
Thx for the link! That could indeed be very helpful!

**Comment by nickgr6** [comment]
You're welcome! I'm looking forward to the contents of the fix:)

**Comment by nickgr6** [comment]
Any ideas what the impact of the fix will be and when it can be fixed?

**Comment by felixbarny** [comment]
What do you mean with impact of the fix? I figured out a solution. I only need to find some time to implement it. Rough estimate is within the next two weeks as there are currently a lot of things going on.
